// Mocks generated by Mockito 5.4.4 from annotations
// in educode/test/integration/submission_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i11;

import 'package:educode/features/auth/presentation/providers/auth_provider.dart'
    as _i10;
import 'package:educode/features/courses/data/services/activity_service.dart'
    as _i9;
import 'package:educode/features/courses/data/services/submission_service.dart'
    as _i4;
import 'package:educode/features/courses/domain/models/activity_model.dart'
    as _i3;
import 'package:educode/features/courses/domain/models/submission_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubmission_0 extends _i1.SmartFake implements _i2.Submission {
  _FakeSubmission_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityModel_1 extends _i1.SmartFake implements _i3.ActivityModel {
  _FakeActivityModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubmissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmissionService extends _i1.Mock implements _i4.SubmissionService {
  MockSubmissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Submission>> getActivitySubmissions(
    int? activityId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivitySubmissions,
          [
            activityId,
            token,
          ],
        ),
        returnValue: _i5.Future<List<_i2.Submission>>.value(<_i2.Submission>[]),
      ) as _i5.Future<List<_i2.Submission>>);

  @override
  _i5.Future<void> gradeSubmission(
    int? submissionId,
    double? grade,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #gradeSubmission,
          [
            submissionId,
            grade,
            token,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Submission?> getStudentSubmission(
    int? entregaId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentSubmission,
          [
            entregaId,
            token,
          ],
        ),
        returnValue: _i5.Future<_i2.Submission?>.value(),
      ) as _i5.Future<_i2.Submission?>);

  @override
  _i5.Future<_i2.Submission?> getStudentSubmission2(
    int? alumnoId,
    int? actividadId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentSubmission2,
          [
            alumnoId,
            actividadId,
            token,
          ],
        ),
        returnValue: _i5.Future<_i2.Submission?>.value(),
      ) as _i5.Future<_i2.Submission?>);

  @override
  _i5.Future<_i2.Submission> submitActivity(
    int? activityId,
    String? solution,
    String? token, {
    _i6.File? image,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitActivity,
          [
            activityId,
            solution,
            token,
          ],
          {#image: image},
        ),
        returnValue: _i5.Future<_i2.Submission>.value(_FakeSubmission_0(
          this,
          Invocation.method(
            #submitActivity,
            [
              activityId,
              solution,
              token,
            ],
            {#image: image},
          ),
        )),
      ) as _i5.Future<_i2.Submission>);

  @override
  _i5.Future<_i2.Submission> getSubmissionDetails(
    int? submissionId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubmissionDetails,
          [
            submissionId,
            token,
          ],
        ),
        returnValue: _i5.Future<_i2.Submission>.value(_FakeSubmission_0(
          this,
          Invocation.method(
            #getSubmissionDetails,
            [
              submissionId,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Submission>);

  @override
  _i5.Future<_i7.Uint8List> getSubmissionImage(
    int? submissionId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubmissionImage,
          [
            submissionId,
            token,
          ],
        ),
        returnValue: _i5.Future<_i7.Uint8List>.value(_i7.Uint8List(0)),
      ) as _i5.Future<_i7.Uint8List>);

  @override
  _i5.Future<void> evaluateSubmissionWithGemini(
    int? entregaId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #evaluateSubmissionWithGemini,
          [
            entregaId,
            token,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Submission>> getStudentSubmissions(
    int? alumnoId,
    int? asignaturaId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentSubmissions,
          [
            alumnoId,
            asignaturaId,
            token,
          ],
        ),
        returnValue: _i5.Future<List<_i2.Submission>>.value(<_i2.Submission>[]),
      ) as _i5.Future<List<_i2.Submission>>);

  @override
  _i5.Future<String> processImageOCR(
    _i6.File? image,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processImageOCR,
          [
            image,
            token,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #processImageOCR,
            [
              image,
              token,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> getSubmissionImageUrl(
    int? submissionId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubmissionImageUrl,
          [
            submissionId,
            token,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getSubmissionImageUrl,
            [
              submissionId,
              token,
            ],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [ActivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityService extends _i1.Mock implements _i9.ActivityService {
  MockActivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.ActivityModel>> getActivities(
    int? subjectId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivities,
          [
            subjectId,
            token,
          ],
        ),
        returnValue:
            _i5.Future<List<_i3.ActivityModel>>.value(<_i3.ActivityModel>[]),
      ) as _i5.Future<List<_i3.ActivityModel>>);

  @override
  _i5.Future<List<_i3.ActivityModel>> getCourseActivities(
    int? courseId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCourseActivities,
          [
            courseId,
            token,
          ],
        ),
        returnValue:
            _i5.Future<List<_i3.ActivityModel>>.value(<_i3.ActivityModel>[]),
      ) as _i5.Future<List<_i3.ActivityModel>>);

  @override
  _i5.Future<_i3.ActivityModel> createActivity(
    int? subjectId,
    Map<String, dynamic>? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createActivity,
          [
            subjectId,
            data,
            token,
          ],
        ),
        returnValue: _i5.Future<_i3.ActivityModel>.value(_FakeActivityModel_1(
          this,
          Invocation.method(
            #createActivity,
            [
              subjectId,
              data,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ActivityModel>);

  @override
  _i5.Future<_i3.ActivityModel> updateActivity(
    int? activityId,
    Map<String, dynamic>? data,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActivity,
          [
            activityId,
            data,
            token,
          ],
        ),
        returnValue: _i5.Future<_i3.ActivityModel>.value(_FakeActivityModel_1(
          this,
          Invocation.method(
            #updateActivity,
            [
              activityId,
              data,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ActivityModel>);

  @override
  _i5.Future<void> deleteActivity(
    int? activityId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteActivity,
          [
            activityId,
            token,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ActivityModel> getActivity(
    int? activityId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivity,
          [
            activityId,
            token,
          ],
        ),
        returnValue: _i5.Future<_i3.ActivityModel>.value(_FakeActivityModel_1(
          this,
          Invocation.method(
            #getActivity,
            [
              activityId,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ActivityModel>);

  @override
  _i5.Future<String> downloadActivityCsv(
    int? activityId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadActivityCsv,
          [
            activityId,
            token,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #downloadActivityCsv,
            [
              activityId,
              token,
            ],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i10.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<bool> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> checkAuthStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkAuthStatus,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> register(
    String? email,
    String? password,
    String? name,
    String? lastName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            name,
            lastName,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> updateProfile({
    required String? nombre,
    required String? apellidos,
    required String? email,
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #nombre: nombre,
            #apellidos: apellidos,
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
